[package]
name = "av"
version = "3.4.0"
edition = "2024"

[dependencies]
libc = "0.2"
ring = "0.17"
serde_json = "1"
ureq = { version = "3.3", default-features = false, features = ["rustls"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "av"
path = "src/cli/main.rs"

[[bin]]
name = "av-brew-stub"
path = "src/brew_stub/main.rs"

[[bin]]
name = "scanner"
path = "src/scanner/main.rs"
