use super::*;

pub(crate) const SYSTEM_TMP_ROOT: &str = "/tmp";

pub(crate) const BREW_PACKAGE_PREFIX: &str = "brew:";

pub(crate) const CASK_PACKAGE_PREFIX: &str = "cask:";

pub(crate) const ISOTOPE_PACKAGE_PREFIX: &str = "isotope:";

pub(crate) const VENDOR_PACKAGE_PREFIX: &str = "av:";

pub(crate) const ISOTOPE_INSTALL_ROOT_DIR: &str = "iso";

pub(crate) const PKG_STATE_LOCK: &str = ".pkg.lock";

pub(crate) const ROOT_RECEIPT: &str = ".pkg/root-receipt.json";

pub(crate) const RECEIPTS_DIR: &str = ".pkg/receipts";

pub(crate) const ROOT_EXECUTABLES_MANIFEST: &str = ".pkg/root-executables.json";

pub(crate) const ROOT_OWNERSHIP_MANIFEST: &str = ".pkg/root-owned-paths.json";

pub(crate) const STUB_MANIFEST: &str = ".pkg/stubs.json";

pub(crate) const STUB_HEADER: &str = "# generated by av";

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum EmbeddedPackage {
    Formula(String),
    Cask(String),
    NpmPackage(String),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum PackageAliasTarget {
    HomebrewFormula(String),
    HomebrewCask(String),
    VendorPackage(String),
    NpmPackage(String),
    PipPackage(String),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RequestedPackage {
    Auto(String),
    HomebrewFormula(String),
    HomebrewCask(String),
    VendorPackage(String),
    Isotope(String),
    NpmPackage {
        package: String,
        version: Option<String>,
    },
    PipPackage(String),
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct IRequest {
    pub(crate) packages: Vec<RequestedPackage>,
    pub(crate) force: bool,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct UninstallRequest {
    pub(crate) packages: Vec<String>,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct UpdateRequest {
    pub(crate) selection: PackageSelection,
    pub(crate) no_self_update: bool,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct PackageStatusRequest {
    pub(crate) selection: PackageSelection,
    pub(crate) output: OutputMode,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct InfoRequest {
    pub(crate) package: RequestedPackage,
    pub(crate) output: OutputMode,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct SearchRequest {
    pub(crate) query: String,
    pub(crate) output: OutputMode,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum OutputMode {
    Human,
    Json,
    Jsonl,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) enum PackageSelection {
    AllInstalled,
    Requested(Vec<RequestedPackage>),
}

#[derive(Debug, Clone)]
pub(crate) struct InstallPlan {
    pub(crate) mode: Mode,
    pub(crate) package_name: String,
    pub(crate) root_formula: String,
    pub(crate) stable_root: PathBuf,
    pub(crate) install_root: PathBuf,
    pub(crate) tmp_root: PathBuf,
}

#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct InstallReceipt {
    pub(crate) formula: String,
    pub(crate) version: String,
    pub(crate) bottle_sha256: String,
    pub(crate) bottle_tag: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) owned_paths: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct PackageReceipt {
    pub(crate) package_name: String,
    pub(crate) version: String,
    pub(crate) source: PackageReceiptSource,
    #[serde(default)]
    pub(crate) metadata: PackageMetadata,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub(crate) enum PackageReceiptSource {
    Formula { root_formula: String },
    Cask { cask_name: String },
    Isotope { isotope_name: String },
    Vendor { vendor_name: String },
    Npm { package_name: String },
    Pip { package_name: String },
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct PackageMetadata {
    pub(crate) description: Option<String>,
    pub(crate) homepage: Option<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct InstalledPackageRecord {
    pub(crate) package_name: String,
    pub(crate) source: PackageReceiptSource,
    pub(crate) installed_version: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct PackageStatus {
    pub(crate) package_name: String,
    pub(crate) source: PackageReceiptSource,
    pub(crate) installed_version: String,
    pub(crate) latest_version: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct PackageInfo {
    pub(crate) package_name: String,
    pub(crate) qualified_name: String,
    pub(crate) install_root: PathBuf,
    pub(crate) installed: bool,
    pub(crate) source: Option<PackageReceiptSource>,
    pub(crate) source_error: Option<String>,
    pub(crate) aliases: Vec<String>,
    pub(crate) aliases_error: Option<String>,
    pub(crate) installed_version: Option<String>,
    pub(crate) latest_version: Option<String>,
    pub(crate) latest_version_error: Option<String>,
    pub(crate) executable_paths: Vec<String>,
    pub(crate) executable_paths_error: Option<String>,
    pub(crate) popularity: Option<EmbeddedPackagePopularity>,
    pub(crate) last_updated_at: Option<String>,
    pub(crate) homebrew_info: Option<HomebrewPackageInfo>,
    pub(crate) homebrew_info_error: Option<String>,
    pub(crate) npm_homepage: Option<String>,
    pub(crate) npm_package_info_error: Option<String>,
    pub(crate) security_state: Option<PackageSecurityState>,
    #[serde(rename = "versionOptions", skip_serializing_if = "Vec::is_empty")]
    pub(crate) version_options: Vec<FormulaVersionOption>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct FormulaVersionOption {
    #[serde(rename = "displayName")]
    pub(crate) display_name: String,
    #[serde(rename = "aliasName")]
    pub(crate) alias_name: Option<String>,
    #[serde(rename = "packageName")]
    pub(crate) package_name: String,
    #[serde(rename = "installPackageName")]
    pub(crate) install_package_name: String,
    #[serde(rename = "rootFormula")]
    pub(crate) root_formula: String,
    pub(crate) version: Option<String>,
    #[serde(rename = "installRoot")]
    pub(crate) install_root: PathBuf,
    pub(crate) installed: bool,
    #[serde(rename = "stubActive")]
    pub(crate) stub_active: bool,
    #[serde(rename = "isLatest")]
    pub(crate) is_latest: bool,
    #[serde(rename = "isRecommended")]
    pub(crate) is_recommended: bool,
    #[serde(rename = "supportsSideBySideStubs")]
    pub(crate) supports_side_by_side_stubs: bool,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct HomebrewPackageInfo {
    pub(crate) formula: String,
    pub(crate) description: Option<String>,
    pub(crate) homepage: Option<String>,
    pub(crate) repository: Option<String>,
    #[serde(rename = "upstreamDocs", skip_serializing_if = "Option::is_none")]
    pub(crate) upstream_docs: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) docs: Vec<String>,
    pub(crate) license: Option<String>,
    pub(crate) dependencies: Vec<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct PackageSearchResult {
    pub(crate) package_name: String,
    pub(crate) source: PackageReceiptSource,
    pub(crate) summary: Option<String>,
    pub(crate) latest_version: Option<String>,
    pub(crate) homepage: Option<String>,
    pub(crate) repository: Option<String>,
    pub(crate) upstream_docs: Option<String>,
    pub(crate) docs: Vec<String>,
    pub(crate) category: Option<String>,
    pub(crate) dependencies: Vec<String>,
    pub(crate) install_package_names: Vec<String>,
    pub(crate) security_state: Option<PackageSecurityState>,
    pub(crate) rank: Option<u32>,
    pub(crate) last_updated_at: Option<String>,
    pub(crate) pulse_kind: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct InstalledPackageRef {
    pub(crate) package_name: String,
    pub(crate) install_root: PathBuf,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct StubManifest {
    pub(crate) stubs: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct InstallOptions {
    pub(crate) intent: InstallIntent,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum InstallIntent {
    Install,
    Reinstall,
    Update,
}

pub(crate) struct PackageMutationLock {
    pub(crate) file: File,
}

impl InstallPlan {
    pub(crate) fn for_i(package_name: String, root_formula: String) -> Self {
        let opt_root = opt_pkg_root();
        let stable_root = opt_root.join(&package_name);
        let install_root = opt_root.join(&package_name);
        Self {
            mode: Mode::I,
            package_name,
            root_formula,
            stable_root,
            install_root,
            tmp_root: temp_root_for_target_root(
                &opt_root,
                Path::new(SYSTEM_TMP_ROOT),
                Path::new(TMP_TOOL_ROOT),
            ),
        }
    }

    pub(crate) fn for_i_npm(package_name: String, root_formula: String, npm_package: &str) -> Self {
        let npm_root = opt_npm_root();
        let stable_root = npm_root.join(npm_package_install_relative_path(npm_package));
        let install_root = stable_root.clone();
        Self {
            mode: Mode::I,
            package_name,
            root_formula,
            stable_root,
            install_root,
            tmp_root: temp_root_for_target_root(
                &npm_root,
                Path::new(SYSTEM_TMP_ROOT),
                Path::new(TMP_TOOL_ROOT),
            ),
        }
    }

    pub(crate) fn for_i_pip(package_name: String, root_formula: String, pip_package: &str) -> Self {
        let pip_root = opt_pip_root();
        let stable_root = pip_root.join(pip_package_install_leaf_name(pip_package));
        let install_root = stable_root.clone();
        Self {
            mode: Mode::I,
            package_name,
            root_formula,
            stable_root,
            install_root,
            tmp_root: temp_root_for_target_root(
                &pip_root,
                Path::new(SYSTEM_TMP_ROOT),
                Path::new(TMP_TOOL_ROOT),
            ),
        }
    }

    pub(crate) fn for_i_isotope(package_name: String, isotope_name: &str) -> Self {
        let isotope_root = opt_pkg_root().join(ISOTOPE_INSTALL_ROOT_DIR);
        let stable_root = isotope_root.join(isotope_name);
        let install_root = stable_root.clone();
        Self {
            mode: Mode::I,
            package_name: package_name.clone(),
            root_formula: package_name,
            stable_root,
            install_root,
            tmp_root: temp_root_for_target_root(
                &isotope_root,
                Path::new(SYSTEM_TMP_ROOT),
                Path::new(TMP_TOOL_ROOT),
            ),
        }
    }

    pub(crate) fn for_i_radioisotope(package_name: String, root_formula: String) -> Self {
        let opt_root = opt_pkg_root();
        let stable_root = opt_root.join(&root_formula);
        let install_root = stable_root.clone();
        Self {
            mode: Mode::I,
            package_name,
            root_formula,
            stable_root,
            install_root,
            tmp_root: temp_root_for_target_root(
                &opt_root,
                Path::new(SYSTEM_TMP_ROOT),
                Path::new(TMP_TOOL_ROOT),
            ),
        }
    }

    pub(crate) fn actual_target_dir(&self, _formula: &str) -> PathBuf {
        self.install_root.clone()
    }

    pub(crate) fn stable_target_dir(&self, _formula: &str) -> PathBuf {
        self.stable_root.clone()
    }

    pub(crate) fn receipt_path(&self, formula: &str) -> PathBuf {
        self.install_root
            .join(RECEIPTS_DIR)
            .join(format!("{formula}.json"))
    }

    pub(crate) fn package_manifest_path(&self) -> PathBuf {
        self.install_root.join(STUB_MANIFEST)
    }

    pub(crate) fn root_receipt_path(&self) -> PathBuf {
        self.install_root.join(ROOT_RECEIPT)
    }

    pub(crate) fn root_executables_manifest_path(&self) -> PathBuf {
        self.install_root.join(ROOT_EXECUTABLES_MANIFEST)
    }

    pub(crate) fn root_ownership_manifest_path(&self) -> PathBuf {
        self.install_root.join(ROOT_OWNERSHIP_MANIFEST)
    }
}

pub(crate) fn acquire_package_mutation_lock() -> Result<PackageMutationLock, String> {
    acquire_package_mutation_lock_at(&opt_pkg_root())
}

pub(crate) fn acquire_package_mutation_lock_at(root: &Path) -> Result<PackageMutationLock, String> {
    fs::create_dir_all(root)
        .map_err(|err| format!("failed to create {}: {err}", root.display()))?;
    let path = root.join(PKG_STATE_LOCK);
    let file = File::options()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(&path)
        .map_err(|err| format!("failed to open {}: {err}", path.display()))?;
    let result = unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_EX) };
    if result != 0 {
        return Err(format!(
            "failed to lock {}: {}",
            path.display(),
            std::io::Error::last_os_error()
        ));
    }
    Ok(PackageMutationLock { file })
}

impl Drop for PackageMutationLock {
    fn drop(&mut self) {
        unsafe {
            libc::flock(self.file.as_raw_fd(), libc::LOCK_UN);
        }
    }
}

pub(crate) fn load_or_resolve_package_receipt(
    package_name: &str,
    install_root: &Path,
) -> Result<PackageReceipt, String> {
    load_package_receipt(&install_root.join(ROOT_RECEIPT))?
        .ok_or_else(|| format!("package {package_name} is installed but missing package metadata"))
}

pub(crate) fn load_package_receipt(path: &Path) -> Result<Option<PackageReceipt>, String> {
    let data = match fs::read(path) {
        Ok(data) => data,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => return Err(format!("failed to read {}: {err}", path.display())),
    };
    let receipt = serde_json::from_slice(&data)
        .map_err(|err| format!("failed to parse {}: {err}", path.display()))?;
    Ok(Some(receipt))
}

pub(crate) fn write_package_receipt(path: &Path, receipt: &PackageReceipt) -> Result<(), String> {
    let data = serde_json::to_vec_pretty(receipt)
        .map_err(|err| format!("failed to serialize package receipt: {err}"))?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("failed to create {}: {err}", parent.display()))?;
    }
    fs::write(path, data).map_err(|err| format!("failed to write {}: {err}", path.display()))
}
