use super::*;

pub(crate) const BREW_PACKAGE_PREFIX: &str = "brew:";

pub(crate) const CASK_PACKAGE_PREFIX: &str = "cask:";

pub(crate) const ISOTOPE_PACKAGE_PREFIX: &str = "isotope:";

pub(crate) const VENDOR_PACKAGE_PREFIX: &str = "av:";

pub(crate) const ISOTOPE_INSTALL_ROOT_DIR: &str = "iso";

pub(crate) const PKG_STATE_LOCK: &str = ".pkg.lock";

pub(crate) const ROOT_RECEIPT: &str = ".pkg/root-receipt.json";

pub(crate) const RECEIPTS_DIR: &str = ".pkg/receipts";

pub(crate) const ROOT_EXECUTABLES_MANIFEST: &str = ".pkg/root-executables.json";

pub(crate) const ROOT_OWNERSHIP_MANIFEST: &str = ".pkg/root-owned-paths.json";

pub(crate) const STUB_MANIFEST: &str = ".pkg/stubs.json";

pub(crate) const STUB_HEADER: &str = "# generated by av";

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum EmbeddedPackage {
    Formula(String),
    Cask(String),
    NpmPackage(String),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum PackageAliasTarget {
    HomebrewFormula(String),
    HomebrewCask(String),
    VendorPackage(String),
    NpmPackage(String),
    PipPackage(String),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RequestedPackage {
    Auto(String),
    HomebrewFormula(String),
    HomebrewCask(String),
    VendorPackage(String),
    Isotope(String),
    NpmPackage {
        package: String,
        version: Option<String>,
    },
    PipPackage(String),
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct IRequest {
    pub(crate) packages: Vec<RequestedPackage>,
    pub(crate) force: bool,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct UninstallRequest {
    pub(crate) packages: Vec<String>,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct UpdateRequest {
    pub(crate) selection: PackageSelection,
    pub(crate) no_self_update: bool,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct PackageStatusRequest {
    pub(crate) selection: PackageSelection,
    pub(crate) output: OutputMode,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct InfoRequest {
    pub(crate) package: RequestedPackage,
    pub(crate) output: OutputMode,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct SearchRequest {
    pub(crate) query: String,
    pub(crate) output: OutputMode,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum OutputMode {
    Human,
    Json,
    Jsonl,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) enum PackageSelection {
    AllInstalled,
    Requested(Vec<RequestedPackage>),
}

#[derive(Debug, Clone)]
pub(crate) struct InstallPlan {
    pub(crate) mode: Mode,
    pub(crate) package_name: String,
    pub(crate) root_formula: String,
    pub(crate) stable_root: PathBuf,
    pub(crate) install_root: PathBuf,
    pub(crate) tmp_root: PathBuf,
}

#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct InstallReceipt {
    pub(crate) formula: String,
    pub(crate) version: String,
    pub(crate) bottle_sha256: String,
    pub(crate) bottle_tag: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) owned_paths: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct PackageReceipt {
    pub(crate) package_name: String,
    pub(crate) version: String,
    pub(crate) source: PackageReceiptSource,
    #[serde(default)]
    pub(crate) metadata: PackageMetadata,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub(crate) enum PackageReceiptSource {
    Formula { root_formula: String },
    Cask { cask_name: String },
    Isotope { isotope_name: String },
    Vendor { vendor_name: String },
    Npm { package_name: String },
    Pip { package_name: String },
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct PackageMetadata {
    pub(crate) description: Option<String>,
    pub(crate) homepage: Option<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct InstalledPackageRecord {
    pub(crate) package_name: String,
    pub(crate) source: PackageReceiptSource,
    pub(crate) installed_version: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct PackageStatus {
    pub(crate) package_name: String,
    pub(crate) source: PackageReceiptSource,
    pub(crate) installed_version: String,
    pub(crate) latest_version: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct PackageInfo {
    pub(crate) package_name: String,
    pub(crate) qualified_name: String,
    pub(crate) install_root: PathBuf,
    pub(crate) installed: bool,
    pub(crate) source: Option<PackageReceiptSource>,
    pub(crate) source_error: Option<String>,
    pub(crate) aliases: Vec<String>,
    pub(crate) aliases_error: Option<String>,
    pub(crate) installed_version: Option<String>,
    pub(crate) latest_version: Option<String>,
    pub(crate) latest_version_error: Option<String>,
    pub(crate) executable_paths: Vec<String>,
    pub(crate) executable_paths_error: Option<String>,
    pub(crate) popularity: Option<EmbeddedPackagePopularity>,
    pub(crate) last_updated_at: Option<String>,
    pub(crate) homebrew_info: Option<HomebrewPackageInfo>,
    pub(crate) homebrew_info_error: Option<String>,
    pub(crate) npm_homepage: Option<String>,
    pub(crate) npm_package_info_error: Option<String>,
    pub(crate) security_state: Option<PackageSecurityState>,
    #[serde(rename = "versionOptions", skip_serializing_if = "Vec::is_empty")]
    pub(crate) version_options: Vec<FormulaVersionOption>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct FormulaVersionOption {
    #[serde(rename = "displayName")]
    pub(crate) display_name: String,
    #[serde(rename = "aliasName")]
    pub(crate) alias_name: Option<String>,
    #[serde(rename = "packageName")]
    pub(crate) package_name: String,
    #[serde(rename = "installPackageName")]
    pub(crate) install_package_name: String,
    #[serde(rename = "rootFormula")]
    pub(crate) root_formula: String,
    pub(crate) version: Option<String>,
    #[serde(rename = "installRoot")]
    pub(crate) install_root: PathBuf,
    pub(crate) installed: bool,
    #[serde(rename = "stubActive")]
    pub(crate) stub_active: bool,
    #[serde(rename = "isLatest")]
    pub(crate) is_latest: bool,
    #[serde(rename = "isRecommended")]
    pub(crate) is_recommended: bool,
    #[serde(rename = "supportsSideBySideStubs")]
    pub(crate) supports_side_by_side_stubs: bool,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct HomebrewPackageInfo {
    pub(crate) formula: String,
    pub(crate) description: Option<String>,
    pub(crate) homepage: Option<String>,
    pub(crate) repository: Option<String>,
    #[serde(rename = "upstreamDocs", skip_serializing_if = "Option::is_none")]
    pub(crate) upstream_docs: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) docs: Vec<String>,
    pub(crate) license: Option<String>,
    pub(crate) dependencies: Vec<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct PackageSearchResult {
    pub(crate) package_name: String,
    pub(crate) source: PackageReceiptSource,
    pub(crate) summary: Option<String>,
    pub(crate) latest_version: Option<String>,
    pub(crate) homepage: Option<String>,
    pub(crate) repository: Option<String>,
    pub(crate) upstream_docs: Option<String>,
    pub(crate) docs: Vec<String>,
    pub(crate) category: Option<String>,
    pub(crate) dependencies: Vec<String>,
    pub(crate) install_package_names: Vec<String>,
    pub(crate) security_state: Option<PackageSecurityState>,
    pub(crate) rank: Option<u32>,
    pub(crate) last_updated_at: Option<String>,
    pub(crate) pulse_kind: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct InstalledPackageRef {
    pub(crate) package_name: String,
    pub(crate) install_root: PathBuf,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct StubManifest {
    pub(crate) stubs: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct InstallOptions {
    pub(crate) intent: InstallIntent,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum InstallIntent {
    Install,
    Reinstall,
    Update,
}

pub(crate) struct PackageMutationLock {
    pub(crate) file: File,
}
