name: Rust Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  coveralls:
    name: Coveralls
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate isotope metadata
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/build-isotopes.sh --skip-builds

      - name: Generate package database
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/build-db.py

      - name: Generate combined database
        run: scripts/build-combined-json.py

      - name: Generate Rust coverage
        run: >
          cargo llvm-cov --workspace --lcov --output-path lcov.info

      - name: Upload Rust coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
          format: lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
